INSERT INTO i18n (i18n_id , label , val, iso3language )
VALUES
(NULL, 'Add_a_Comment', 'Add a Comment  ', 'eng'),
(NULL, 'alias_previously_used_on_line', 'alias previously used on line  ', 'eng'),
(NULL, 'already_at_beginning', 'You are already at the beginning.  ', 'eng'),
(NULL, 'already_at_end_of_interview', 'You are already at the end of interview.  Thanks again.  ', 'eng'),
(NULL, 'and', 'and  ', 'eng'),
(NULL, 'answerChoices_must_be_specified', 'answerChoices must be specified  ', 'eng'),
(NULL, 'answerChoice_value_already_used', 'answerChoice value already used:  ', 'eng'),
(NULL, 'answerOptions_column_missing', 'answerOptions column is missing  ', 'eng'),
(NULL, 'answer_this_question', 'Please answer this question  ', 'eng'),
(NULL, 'before_proceeding', ' before proceeding  ', 'eng'),
(NULL, 'closing_braces', ' closing brace(s)  ', 'eng'),
(NULL, 'column', ' column  ', 'eng'),
(NULL, 'conceptName_may_not_begin_with_a_digit', 'conceptName may not begin with a digit - prepending \'_\':  ', 'eng'),
(NULL, 'CURRENT_QUESTIONS', 'CURRENT QUESTION(s)  ', 'eng'),
(NULL, 'DATE', 'Date ', 'eng'),
(NULL, 'DAY', 'Day ', 'eng'),
(NULL, 'dependencies_column_is_missing', 'dependencies column is missing  ', 'eng'),
(NULL, 'disallowed_for_security_reasons', 'disallowed for security reasons  ', 'eng'),
(NULL, 'does_not_exist', 'does not exist  ', 'eng'),
(NULL, 'ending_tags_may_not_have_attribute_value_pairs', 'ending tags may not have attribute values pairs  ', 'eng'),
(NULL, 'Enter_a_comment_for_this_question', 'Enter a comment for this question  ', 'eng'),
(NULL, 'Enter_password_for_Administrative_Mode', 'Enter password to enter Administrative Mode  ', 'eng'),
(NULL, 'entry_into_admin_mode_disallowed', 'You do not currently have permission to be in Admin Mode  ', 'eng'),
(NULL, 'error_accessing_file', 'error accessing file:  ', 'eng'),
(NULL, 'error_building_sorted_list_of_interviews', 'Error building sorted list of interviews:  ', 'eng'),
(NULL, 'error_closing_file', 'Error closing file:  ', 'eng'),
(NULL, 'error_closing_reader', 'error closing reader:  ', 'eng'),
(NULL, 'error_closing_writer', 'Error closing writer:  ', 'eng'),
(NULL, 'error_file', 'Error: file  ', 'eng'),
(NULL, 'error_getting_list_of_available_interviews', 'Error getting list of available interviews:  ', 'eng'),
(NULL, 'Error_loading_datafile', 'Error loading datafile:  ', 'eng'),
(NULL, 'error_null_filename', 'Error: null filename  ', 'eng'),
(NULL, 'error_parsing_time', 'Error parsing time  ', 'eng'),
(NULL, 'Error_reading_from', 'Error reading from  ', 'eng'),
(NULL, 'error_writing_to', 'Error writing to  ', 'eng'),
(NULL, 'evals_disallowed_within_question_block', 'Should not have expression evaluations within a query block (brace level  ', 'eng'),
(NULL, 'evaluate_expr', 'evaluate expr', 'eng'),
(NULL, 'evaluations_disallowed_within_block', '\'e\' actionTypes not allowed within a group of nodes - line  ', 'eng'),
(NULL, 'EVIDENCE_AREA', 'EVIDENCE AREA  ', 'eng'),
(NULL, 'expected_equals_sign', 'expected equals sign in  ', 'eng'),
(NULL, 'expected_start_of_a_string', 'expected the start of a string in  ', 'eng'),
(NULL, 'expects', '() expects  ', 'eng'),
(NULL, 'extra_closing_brace', 'Extra closing brace  ', 'eng'),
(NULL, 'extra_closing_brace_at_line', 'extra closing brace - line  ', 'eng'),
(NULL, 'extra_opening_brace', 'extra opening brace  ', 'eng'),
(NULL, 'function', 'function  ', 'eng'),
(NULL, 'Help', 'Help', 'eng'),
(NULL, 'HOUR', 'Hour ', 'eng'),
(NULL, 'incorrect_password', 'Incorrect password.  Please try again.  ', 'eng'),
(NULL, 'incorrect_password_for_admin_mode', 'Incorrect password to enter Administrative Mode  ', 'eng'),
(NULL, 'incorrect_syntax_for', 'Incorrect syntax for  ', 'eng'),
(NULL, 'inserting_missing_endTag_for', 'inserting missing endTag for  ', 'eng'),
(NULL, 'Internal_error__Unexpected_data_format', 'Internal error: Unexpected data format:  ', 'eng'),
(NULL, 'interview_saved_successfully_as', 'Interview saved successfully as  ', 'eng'),
(NULL, 'invalid_action_type', 'Invalid action type  ', 'eng'),
(NULL, 'invalid_answerType', 'invalid answerType  ', 'eng'),
(NULL, 'invalid_dataType', 'Invalid datum type:  ', 'eng'),
(NULL, 'invalid_end_tag', 'invalid end tag  ', 'eng'),
(NULL, 'invalid_formatting_mask', 'Invalid formatting mask:  ', 'eng'),
(NULL, 'invalid_node_at_step', 'Invalid node at step  ', 'eng'),
(NULL, 'invalid_number_for_starting_step', 'Invalid number for starting step:  ', 'eng'),
(NULL, 'invalid_number_for_field_width', 'Invalid number for field width:  ', 'eng'),
(NULL, 'invalid_questionOrEvalType', 'Invalid questionOrEvalType:  ', 'eng'),
(NULL, 'in_the_range', ' in the range:  ', 'eng'),
(NULL, 'is_not_accessible', ' is not accessible  ', 'eng'),
(NULL, 'is_not_a_directory', ' is not a directory  ', 'eng'),
(NULL, 'is_not_a_file', ' is not a file  ', 'eng'),
(NULL, 'jump_to', 'jump to:', 'eng'),
(NULL, 'languageNum_must_be_an_integer', 'languageNum must be an integer:  ', 'eng'),
(NULL, 'languageNum_must_be_in_range_zero_to', 'languageNum must be in range (0 -  ', 'eng'),
(NULL, 'line', 'line  ', 'eng'),
(NULL, 'localName_may_not_begin_with_a_digit', 'localName may not begin with a digit - prepending \'_\':  ', 'eng'),
(NULL, 'localName_must_be_specified', 'localName must be specified  ', 'eng'),
(NULL, 'localName_should_only_contain_letters_digits_and_underscores', 'localName should only contain letters, digits, and underscores ', 'eng'),
(NULL, 'LogoMessage', 'Logo', 'eng'),
(NULL, 'max_less_than_min', 'max value less than min value:  ', 'eng'),
(NULL, 'MINUTE', 'Minute ', 'eng'),
(NULL, 'mismatch_across_languages_in_answerType', 'mismatch across languages in answerType  ', 'eng'),
(NULL, 'mismatch_across_languages_in_number_of_answerChoices', 'mismatch across languages in number of answerChoices:  ', 'eng'),
(NULL, 'mismatch_across_languages_in_return_value_for_answerChoice_num', 'mismatch across languages in return value for answerChoice #  ', 'eng'),
(NULL, 'missing', 'missing  ', 'eng'),
(NULL, 'missing_display_type', 'missing display type  ', 'eng'),
(NULL, 'missing_message_for_answerChoice_num', 'missing message for answerChoice #  ', 'eng'),
(NULL, 'missing_value_or_message_for_answerChoice_num', 'Missing value or message for answerChoice #  ', 'eng'),
(NULL, 'MONTH', 'Month ', 'eng'),
(NULL, 'MONTH_NUM', 'Month (as number) ', 'eng'),
(NULL, 'name_contains_invalid_character', 'name contains invalid character:  ', 'eng'),
(NULL, 'new_variable_will_be_transient', 'new variable will be transient:  ', 'eng'),
(NULL, 'next', 'next', 'eng'),
(NULL, 'node_does_not_exist', 'Node does not exist  ', 'eng'),
(NULL, 'node_does_not_exist_within_schedule', 'Unable to find index for node:  ', 'eng'),
(NULL, 'node_not_found', 'Node not found:  ', 'eng'),
(NULL, 'not_recognized', ' not recognized [  ', 'eng'),
(NULL, 'not_yet_suppported___line', ' not yet suppported - line  ', 'eng'),
(NULL, 'no_closing_right_angle_bracket', 'no closing right angle bracket  ', 'eng'),
(NULL, 'no_syntax_errors_found', 'No syntax errors were found  ', 'eng'),
(NULL, 'null_datum', 'null Datum  ', 'eng'),
(NULL, 'null_node', 'null Node name  ', 'eng'),
(NULL, 'null_node_at_index', 'null node at index #  ', 'eng'),
(NULL, 'NUMBER', 'Number ', 'eng'),
(NULL, 'numLanguages_must_be_greater_than_zero', 'numLanguages must be greater than zero:  ', 'eng'),
(NULL, 'OFF', 'OFF  ', 'eng'),
(NULL, 'ON', 'ON  ', 'eng'),
(NULL, 'opening_braces', ' opening braces  ', 'eng'),
(NULL, 'or', 'or  ', 'eng'),
(NULL, 'or_restore_an_interview_in_progress', 'OR, restore an interview/questionnaire in progress:  ', 'eng'),
(NULL, 'parameters', ' parameter(s)  ', 'eng'),
(NULL, 'please_answer_the_questions_listed_in', 'Please answer the question(s) listed in  ', 'eng'),
(NULL, 'Please_answer_this_question', 'Please answer this question  ', 'eng'),
(NULL, 'please_enter_a', 'Please enter a  ', 'eng'),
(NULL, 'please_select_an_interview', 'Please select an interview from the drop-down list:  ', 'eng'),
(NULL, 'prematurely_terminated_element', 'prematurely terminated element - expecting  ', 'eng'),
(NULL, 'previous', 'previous', 'eng'),
(NULL, 'questionOrEvalTypeField_must_exist', 'questionOrEvalTypeField must be exist  ', 'eng'),
(NULL, 'QUESTION_AREA', 'QUESTION AREA  ', 'eng'),
(NULL, 'RED', ' RED  ', 'eng'),
(NULL, 'rejecting_mismatched_endTag', 'rejecting mismatched endTag  ', 'eng'),
(NULL, 'reload_questions', 'reload questions', 'eng'),
(NULL, 'restart_clean', 'restart (clean)', 'eng'),
(NULL, 'RESTORE', 'RESTORE', 'eng'),
(NULL, 'restoring_original_schedule', ' - restoring original schedule  ', 'eng'),
(NULL, 'save_to', 'save to:', 'eng'),
(NULL, 'schedule_restored_successfully', 'Schedule restored successfully  ', 'eng'),
(NULL, 'SECOND', 'Second ', 'eng'),
(NULL, 'select_new_interview', 'select new interview', 'eng'),
(NULL, 'select_one_of_the_following', '--Select one of the following--  ', 'eng'),
(NULL, 'Set_as_Not_Understood', 'Set as Not Understood  ', 'eng'),
(NULL, 'Set_as_Refused', 'Set as Refused  ', 'eng'),
(NULL, 'Set_as_Unknown', 'Set as Unknown  ', 'eng'),
(NULL, 'show_Syntax_Errors', 'show Syntax Errors', 'eng'),
(NULL, 'stack_underflow', 'stack underflow  ', 'eng'),
(NULL, 'starting_nested_group_at_line', 'Warning - starting nested group (opening brace) at line ', 'eng'),
(NULL, 'START', 'START', 'eng'),
(NULL, 'STRING', 'String ', 'eng'),
(NULL, 'syntax_error_creating_node', 'Syntax error creating node:  ', 'eng'),
(NULL, 'The_following_data_access_errors_were', 'The following data access errors were found  ', 'eng'),
(NULL, 'The_following_flow_errors_were_found', 'The following flow errors were found  ', 'eng'),
(NULL, 'The_following_syntax_errors_were_found', 'The following syntax errors were found in file  ', 'eng'),
(NULL, 'the_interview_is_completed', 'Thank you for using our survey.<br/><br/>Click <a href="JavaScript:top.close();">here</a> to close this browser window.', 'eng'),
(NULL, 'TIME', 'Time ', 'eng'),
(NULL, 'tried_to_switch_to_unsupported_language', 'Tried to switch to unsupported language  ', 'eng'),
(NULL, 'turn_debugMode', 'toggle debugMode', 'eng'),
(NULL, 'turn_developerMode', 'toggle developerMode', 'eng'),
(NULL, 'turn_showQuestionNum', 'toggle showQuestionNum', 'eng'),
(NULL, 'unable_to_access', 'Unable to access  ', 'eng'),
(NULL, 'unable_to_find_or_access_schedule', 'Unable to find or access schedule  ', 'eng'),
(NULL, 'Unable_to_write_schedule_file', 'Unable to write schedule file:  ', 'eng'),
(NULL, 'unary_tags_may_not_have_closing_tags', 'unary tags may not have closing tags  ', 'eng'),
(NULL, 'undefined_variable', 'undefined variable  ', 'eng'),
(NULL, 'unexpected_error', 'Internal error:  ', 'eng'),
(NULL, 'Unexpected_error_reading_from', 'Unexpected error reading from  ', 'eng'),
(NULL, 'unexpected_error_while_HTMLizing_string', 'Unexpected error while HTMLizing string  ', 'eng'),
(NULL, 'unknown_actionType_at_line', 'unknown actionType for node - line  ', 'eng'),
(NULL, 'unknown_node', 'unknown node  ', 'eng'),
(NULL, 'unknown_special_datatype', 'Unknown special datatype  ', 'eng'),
(NULL, 'unsupported_function', 'unsupported function  ', 'eng'),
(NULL, 'unterminated_escaped_character', 'unterminated escape character   ', 'eng'),
(NULL, 'WEEKDAY', 'Weekday ', 'eng'),
(NULL, 'YEAR', 'Year ', 'eng'),
(NULL, 'at_index', 'at index', 'eng'),
(NULL, 'index_too_high', 'index too high', 'eng'),
(NULL, 'index_too_low', 'index too low', 'eng'),
(NULL, 'expects', ' expects ', 'eng'),
(NULL, 'function', 'function ', 'eng'),
(NULL, 'parameters', ' parameters', 'eng'),
(NULL, 'got', ' got ', 'eng'),
(NULL, 'error_changing_filenames', 'error changing filenames ', 'eng'),
(NULL, 'already_exists', ' already exists', 'eng'),
(NULL, 'unable_to_move_event_logs', 'unable to move events logs to ', 'eng'),
(NULL, 'sign_schedule', 'sign and save schedule', 'eng'),
(NULL, 'signed_schedule_saved_as', 'signed schedule saved as ', 'eng'),
(NULL, 'unable_to_save_signed_schedule', 'unable to save signed schedule', 'eng'),
(NULL, 'jumpToFirstUnasked', 'jump to first unasked', 'eng'),
(NULL, 'suspendToFloppy', 'save to floppy', 'eng'),
(NULL, 'error_saving_data_to', 'error saving data to ', 'eng'),
(NULL, 'error_saving_data_to_completed_dir', 'error saving data to completed dir', 'eng'),
(NULL, 'error_saving_data_to_floppy_dir', 'error saving data to floppy dir', 'eng'),
(NULL, 'your_browser_will_be_redirected_to', 'Your browser will be redirected to ', 'eng'),
(NULL, 'in_three_seconds', ' in three seconds.', 'eng'),
(NULL, 'or_you_can_click_here', 'Or, you can click here to go there immediately:  ', 'eng'),
(NULL, 'RESTORE_FROM_FLOPPY', 'COPY SUSPENDED INTERVIEWS FROM FLOPPY', 'eng'),
(NULL, 'or_restore_from_floppy', 'OR copy all of the suspended interviews from the floppy so they they can be selected to be restored:', 'eng'),
(NULL, 'toggle_EventCollection', 'toggle Event Capture', 'eng'),
(NULL, 'passwords_cannot_be_bypassed', 'passwords cannot be bypassed', 'eng')
;

INSERT INTO i18n (i18n_id , label , val, iso3language )
VALUES
(NULL, 'Add_a_Comment', 'Agrege un comentario ', 'spa'),
(NULL, 'alias_previously_used_on_line', 'Nombre ya  usado  ', 'spa'),
(NULL, 'already_at_beginning', 'Ya estás en el Inicio de la Entrevista  ', 'spa'),
(NULL, 'already_at_end_of_interview', 'Ya estás en el Final de la entrevista. Gracias nuevamente.  ', 'spa'),
(NULL, 'and', 'y  ', 'spa'),
(NULL, 'answerChoices_must_be_specified', 'Especificar (answerChoices) alternativas de respuesta  ', 'spa'),
(NULL, 'answerChoice_value_already_used', 'Valores (answerChoices) ya usados:  ', 'spa'),
(NULL, 'answerOptions_column_missing', 'Falta columna de opciones (answerOptions) de respuesta   ', 'spa'),
(NULL, 'answer_this_question', 'Por favor, responda  a ésta  pregunta  ', 'spa'),
(NULL, 'before_proceeding', 'antes de proceder.', 'spa'),
(NULL, 'closing_braces', 'Corchete ( "]") o llave de cerrar  ', 'spa'),
(NULL, 'column', 'columna  ', 'spa'),
(NULL, 'conceptName_may_not_begin_with_a_digit', 'El concepto (conceptName) no puede empezar con un digito -simulando \'-\':    ', 'spa'),
(NULL, 'CURRENT_QUESTIONS', 'PREGUNTA(S) ACTUAL(ES)  ', 'spa'),
(NULL, 'DATE', 'Fecha ', 'spa'),
(NULL, 'DAY', 'Día ', 'spa'),
(NULL, 'dependencies_column_is_missing', 'Falta columna dependencia (dependencies)', 'spa'),
(NULL, 'disallowed_for_security_reasons', 'Desactivada por razones de seguridad  ', 'spa'),
(NULL, 'does_not_exist', 'no existe  ', 'spa'),
(NULL, 'ending_tags_may_not_have_attribute_value_pairs', 'Expreción final (ending tags) no puede tener valores asignados', 'spa'),
(NULL, 'Enter_a_comment_for_this_question', 'Entre un comentario para ésta pregunta  ', 'spa'),
(NULL, 'Enter_password_for_Administrative_Mode', 'Necesita una clave para entrar al Modo Administrativo (Administrative Mode)  ', 'spa'),
(NULL, 'entry_into_admin_mode_disallowed', 'No tiene permiso para estar en el modo administrativo (Admin Mode)  ', 'spa'),
(NULL, 'error_accessing_file', 'Error al accesar el registro (file): ', 'spa'),
(NULL, 'error_building_sorted_list_of_interviews', 'Error al construir la lista de clasificación de entrevistas:  ', 'spa'),
(NULL, 'error_closing_file', 'Error al cerrar el registro  ', 'spa'),
(NULL, 'error_closing_reader', 'Error al cerrar el lector (reader):  ', 'spa'),
(NULL, 'error_closing_writer', 'Error al cerrar el escritor (writer):  ', 'spa'),
(NULL, 'error_file', 'Error: registro (file) ', 'spa'),
(NULL, 'error_getting_list_of_available_interviews', 'Error al tratar de buscar la lista de entrevistas:  ', 'spa'),
(NULL, 'Error_loading_datafile', 'Error al traer el registro de datos (datafile): ', 'spa'),
(NULL, 'error_null_filename', 'Error: nombre del registro vacío (null filename)  ', 'spa'),
(NULL, 'error_parsing_time', 'Error en el "parsing time"  ', 'spa'),
(NULL, 'Error_reading_from', 'Error de lectura de  ', 'spa'),
(NULL, 'error_writing_to', 'Error al escribir  ', 'spa'),
(NULL, 'evals_disallowed_within_question_block', 'No debería tener expresión de evaluación dentro de un bloque de busqueda ("query block (brace level)")  ', 'spa'),
(NULL, 'evaluate_expr', 'Evalue la Expresión ', 'spa'),
(NULL, 'evaluations_disallowed_within_block', '38-	\'e\' "ActionType" no permitido dentro de un grupo de "nodes" - lineas  ', 'spa'),
(NULL, 'EVIDENCE_AREA', 'AREA DE EVIDENCIAS  ', 'spa'),
(NULL, 'expected_equals_sign', 'Aquí se espera un signo igual dentro  ', 'spa'),
(NULL, 'expected_start_of_a_string', 'Se espera comenzar un de alfanumerico (string)    ', 'spa'),
(NULL, 'expects', '() se espera  ', 'spa'),
(NULL, 'extra_closing_brace', 'Extra corchete de cierre (closing brace)  ', 'spa'),
(NULL, 'extra_closing_brace_at_line', 'Extra corchete de cierre - linea (closing brace - line)  ', 'spa'),
(NULL, 'extra_opening_brace', 'Extra corchete de abertura (opening brace)  ', 'spa'),
(NULL, 'function', 'función  ', 'spa'),
(NULL, 'Help', 'Ayuda ', 'spa'),
(NULL, 'HOUR', 'Hora ', 'spa'),
(NULL, 'incorrect_password', 'Clave incorrecta. Por favor, trate de nuevo.  ', 'spa'),
(NULL, 'incorrect_password_for_admin_mode', 'Clave incorrecta para entrar al Modo Administrivo (Administrative Mode)  ', 'spa'),
(NULL, 'incorrect_syntax_for', 'Sintaxis incorrecta para ', 'spa'),
(NULL, 'inserting_missing_endTag_for', 'Está faltando insertar "endTag"   ', 'spa'),
(NULL, 'Internal_error__Unexpected_data_format', 'Error interno: Inesperado formato de datos  ', 'spa'),
(NULL, 'interview_saved_successfully_as', 'Entrevista guardada exitosamente como  ', 'spa'),
(NULL, 'invalid_action_type', 'Tipo de acción inválida (action type)  ', 'spa'),
(NULL, 'invalid_answerType', 'Tipo de respuesta inválida (answerType)  ', 'spa'),
(NULL, 'invalid_dataType', 'Tipo de dato inválido  ', 'spa'),
(NULL, 'invalid_end_tag', '"Endtag" inválida   ', 'spa'),
(NULL, 'invalid_formatting_mask', '"Formatting mask" invalida  ', 'spa'),
(NULL, 'invalid_node_at_step', 'Nodo (node) invalido en el paso  ', 'spa'),
(NULL, 'invalid_number_for_starting_step', 'Número inválido al comenzar un paso (starting step):  ', 'spa'),
(NULL, 'invalid_number_for_field_width', 'Invalid number for field width:  ', 'spa'),
(NULL, 'invalid_questionOrEvalType', '"questionOrEvalType" invalida:  ', 'spa'),
(NULL, 'in_the_range', 'dentro del intervalo de valores aceptables: ', 'spa'),
(NULL, 'is_not_accessible', 'no está accesible  ', 'spa'),
(NULL, 'is_not_a_directory', 'no es un directorio  ', 'spa'),
(NULL, 'is_not_a_file', 'no es un registro (file)  ', 'spa'),
(NULL, 'jump_to', 'Salta hacia:   ', 'spa'),
(NULL, 'languageNum_must_be_an_integer', '"languageNum" debe ser numero entero:  ', 'spa'),
(NULL, 'languageNum_must_be_in_range_zero_to', '"languageNum" debe estar dentro del intervalo de valores aceptables (0-   ', 'spa'),
(NULL, 'line', 'linea  ', 'spa'),
(NULL, 'localName_may_not_begin_with_a_digit', 'El Nombre interno (internalName) no puede empezar con un número - \'_\':  ', 'spa'),
(NULL, 'localName_must_be_specified', 'Se debe especificar el Nombre interno (internalName)  ', 'spa'),
(NULL, 'localName_should_only_contain_letters_digits_and_underscores', 'El Nombre interno (internalName) debería solamente constar letras, números(enteros), y signo de subrayar ', 'spa'),
(NULL, 'LogoMessage', 'Símbolo "Logo"', 'spa'),
(NULL, 'max_less_than_min', 'Valor máximo menor que valor mínimo:  ', 'spa'),
(NULL, 'MINUTE', 'Minuto ', 'spa'),
(NULL, 'mismatch_across_languages_in_answerType', 'El idioma no corresponde al tipo de respuesta (answerType)  ', 'spa'),
(NULL, 'mismatch_across_languages_in_number_of_answerChoices', 'El idioma no corresponde a las alternativas de respuestas (answerChoices):  ', 'spa'),
(NULL, 'mismatch_across_languages_in_return_value_for_answerChoice_num', 'El idioma no corresponde con el valor para el tipo de respuesta (answerChoice) #  ', 'spa'),
(NULL, 'missing', 'falta  ', 'spa'),
(NULL, 'missing_display_type', 'Falta imágen (display type)  ', 'spa'),
(NULL, 'missing_message_for_answerChoice_num', 'Falta un mensage para alternativa de respuesta (answerChoice) # ', 'spa'),
(NULL, 'missing_value_or_message_for_answerChoice_num', 'Falta un valor o un mensaje para alternativa de respuesta (answerChoice) #  ', 'spa'),
(NULL, 'MONTH', 'Mes ', 'spa'),
(NULL, 'MONTH_NUM', 'Mes (en numero) ', 'spa'),
(NULL, 'name_contains_invalid_character', 'Nombre con letras inválidas:  ', 'spa'),
(NULL, 'new_variable_will_be_transient', 'La nueva variable será transitoria:  ', 'spa'),
(NULL, 'next', 'Próximo  ', 'spa'),
(NULL, 'node_does_not_exist', 'Nodo inexistente  ', 'spa'),
(NULL, 'node_does_not_exist_within_schedule', 'Incapáz de encontrar un index para el nodo:  ', 'spa'),
(NULL, 'node_not_found', 'No se encontró el nodo:  ', 'spa'),
(NULL, 'not_recognized', 'Irreconocible [  ', 'spa'),
(NULL, 'not_yet_suppported___line', 'Linea no suportada todavía -   ', 'spa'),
(NULL, 'no_closing_right_angle_bracket', 'no existe "right angle bracket" de cerrar  ', 'spa'),
(NULL, 'no_syntax_errors_found', 'No se encontraron errores de sistaxis  ', 'spa'),
(NULL, 'null_datum', 'Dato inexistente (null Datum)  ', 'spa'),
(NULL, 'null_node', 'Nombre de Nodo inexistente (null Node name)  ', 'spa'),
(NULL, 'null_node_at_index', 'Nodo inexistente (null node) en el index # ', 'spa'),
(NULL, 'NUMBER', 'Número ', 'spa'),
(NULL, 'numLanguages_must_be_greater_than_zero', 'El número del idioma (numLanguages) debe ser mayor que cero:  ', 'spa'),
(NULL, 'OFF', 'APAGA  ', 'spa'),
(NULL, 'ON', 'PRENDE ', 'spa'),
(NULL, 'opening_braces', 'corchete inicial  ', 'spa'),
(NULL, 'or', 'o  ', 'spa'),
(NULL, 'or_restore_an_interview_in_progress', 'O, restablecer una entrevista / Formulario en ejecución:  ', 'spa'),
(NULL, 'parameters', 'parámetro(s)  ', 'spa'),
(NULL, 'please_answer_the_questions_listed_in', 'Por favor, conteste(n) la(s) pregunta(s) listada(s)  ', 'spa'),
(NULL, 'Please_answer_this_question', 'Por favor, conteste ésta pregunta  ', 'spa'),
(NULL, 'please_enter_a', 'Por favor, entre un  ', 'spa'),
(NULL, 'please_select_an_interview', 'Por favor, seleccione una entrevista de la lista mostrada:  ', 'spa'),
(NULL, 'prematurely_terminated_element', 'elemento, terminado prematuramente - en espera  ', 'spa'),
(NULL, 'previous', 'Previo  ', 'spa'),
(NULL, 'questionOrEvalTypeField_must_exist', 'Debe existir un campo de Tipo/Preg/Eval (questionOrEvalTypeField)  ', 'spa'),
(NULL, 'QUESTION_AREA', 'AREA DE PREGUNTAS  ', 'spa'),
(NULL, 'RED', 'ROJO  ', 'spa'),
(NULL, 'rejecting_mismatched_endTag', '"endTag" rechazado por falta de correspondencia  ', 'spa'),
(NULL, 'reload_questions', 'Recarga preguntas  ', 'spa'),
(NULL, 'restart_clean', 'Partir de nuevo (limpia entrevista)  ', 'spa'),
(NULL, 'RESTORE', 'RESTABLECER  ', 'spa'),
(NULL, 'restoring_original_schedule', 'Restableciendo horario original  ', 'spa'),
(NULL, 'save_to', 'Guarda para:  ', 'spa'),
(NULL, 'schedule_restored_successfully', 'Horario establecido exitosamente  ', 'spa'),
(NULL, 'SECOND', 'Segundo ', 'spa'),
(NULL, 'select_new_interview', 'seleccione una nueva entrevista  ', 'spa'),
(NULL, 'select_one_of_the_following', '--seleccione uno de los siguientes--  ', 'spa'),
(NULL, 'Set_as_Not_Understood', 'Codefique "No se entiende"  ', 'spa'),
(NULL, 'Set_as_Refused', 'Codefique "rechazado"  ', 'spa'),
(NULL, 'Set_as_Unknown', 'Codefique "desconocido"  ', 'spa'),
(NULL, 'show_Syntax_Errors', 'Muestre los errores de sintaxis  ', 'spa'),
(NULL, 'stack_underflow', 'stack underflow  ', 'spa'),
(NULL, 'starting_nested_group_at_line', '131-Atención - Comenzando un grupo dentro de otro (abra corchete) en ésta linea  ', 'spa'),
(NULL, 'START', 'COMIENCE  ', 'spa'),
(NULL, 'STRING', 'Alfanumérico (String) ', 'spa'),
(NULL, 'syntax_error_creating_node', 'Error de sistaxis al crear nodo:  ', 'spa'),
(NULL, 'The_following_data_access_errors_were', 'Se han encontrado los siguientes errores en el acceso de datos ', 'spa'),
(NULL, 'The_following_flow_errors_were_found', 'Se han encontrado los siguientes errores de flujo  ', 'spa'),
(NULL, 'The_following_syntax_errors_were_found', 'Se han encontrado los siguientes errores de sintaxis en el registro  ', 'spa'),
(NULL, 'the_interview_is_completed', 'Gracias, usted ha terminado. Puede <a href="JavaScript:top.close();">cerrar la ventana</a> del "browser".', 'spa'),
(NULL, 'TIME', 'Tiempo ', 'spa'),
(NULL, 'tried_to_switch_to_unsupported_language', 'Trate de conectar con un idioma no soportado  ', 'spa'),
(NULL, 'turn_debugMode', 'Presione "debugMode"  ', 'spa'),
(NULL, 'turn_developerMode', 'Presione "developerMode"  ', 'spa'),
(NULL, 'turn_showQuestionNum', 'Presione "showQuestionNum"  ', 'spa'),
(NULL, 'unable_to_access', 'Incapáz de accesar  ', 'spa'),
(NULL, 'unable_to_find_or_access_schedule', 'Incapáz de encontrar o accesar horario  ', 'spa'),
(NULL, 'Unable_to_write_schedule_file', 'Incapáz de escribir el registro de horario:  ', 'spa'),
(NULL, 'unary_tags_may_not_have_closing_tags', '"unary tags" puede no tener "closing tags"  ', 'spa'),
(NULL, 'undefined_variable', 'variable indefinida  ', 'spa'),
(NULL, 'unexpected_error', 'Error interno:  ', 'spa'),
(NULL, 'Unexpected_error_reading_from', 'Error inesperado de lectura  ', 'spa'),
(NULL, 'unexpected_error_while_HTMLizing_string', 'Error inesperado en HTML alfanumérico (HTMLizing string)  ', 'spa'),
(NULL, 'unknown_actionType_at_line', 'Actión Tipo (actionType) desconocido para el nodo - linea ', 'spa'),
(NULL, 'unknown_node', 'nodo desconocido  ', 'spa'),
(NULL, 'unknown_special_datatype', 'Tipo de dato especial desconocido  ', 'spa'),
(NULL, 'unsupported_function', 'función no soportada  ', 'spa'),
(NULL, 'unterminated_escaped_character', 'Carácter de escape indeterminado   ', 'spa'),
(NULL, 'WEEKDAY', 'Día de Semana ', 'spa'),
(NULL, 'YEAR', 'Año', 'spa'),
(NULL, 'at_index', 'at index', 'spa'),
(NULL, 'index_too_high', 'index too high', 'spa'),
(NULL, 'index_too_low', 'index too low', 'spa'),
(NULL, 'expects', ' expects ', 'spa'),
(NULL, 'function', 'function ', 'spa'),
(NULL, 'parameters', ' parameters', 'spa'),
(NULL, 'got', ' got ', 'spa'),
(NULL, 'error_changing_filenames', 'error changing filenames ', 'spa'),
(NULL, 'already_exists', ' already exists', 'spa'),
(NULL, 'unable_to_move_event_logs', 'unable to move events logs to ', 'spa'),
(NULL, 'sign_schedule', 'Firmar y guardar itinerario', 'spa'),
(NULL, 'signed_schedule_saved_as', 'itinerario firmado guardar como ', 'spa'),
(NULL, 'unable_to_save_signed_schedule', 'incapaz de guardar itenerario firmado', 'spa'),
(NULL, 'jumpToFirstUnasked', 'pasar a primera sin preguntar ', 'spa'),
(NULL, 'suspendToFloppy', 'guardar en floppy', 'spa'),
(NULL, 'error_saving_data_to_completed_dir', 'error guardando datos a Dir Completas', 'spa'),
(NULL, 'error_saving_data_to_floppy_dir', 'error guardando datos a Dir de Floppy', 'spa'),
(NULL, 'error_saving_data_to', 'error guardando datos a ', 'spa'),
(NULL, 'your_browser_will_be_redirected_to', 'Su Browser será redirigido a ', 'spa'),
(NULL, 'in_three_seconds', ' en tres segundos.', 'spa'),
(NULL, 'or_you_can_click_here', 'o puede dar un click aquí para ir inmediatamente allá:  ', 'spa'),
(NULL, 'RESTORE_FROM_FLOPPY', 'copiar entrevistas suspendidas del floppy', 'spa'),
(NULL, 'or_restore_from_floppy', 'o copiar todas las entrevistas suspendidas del floppy para que se pueda seleccionar para restaurar.', 'spa'),
(NULL, 'toggle_EventCollection', 'toggle Event Capture', 'spa'),
(NULL, 'passwords_cannot_be_bypassed', 'passwords cannot be bypassed', 'spa');

INSERT INTO i18n (i18n_id , label , val, iso3language )
VALUES
(NULL, 'Add_a_Comment', 'Добавьте комментарий', 'rus'),
(NULL, 'alias_previously_used_on_line', 'Имя, уже использовавшееся ранее   ', 'rus'),
(NULL, 'already_at_beginning', 'Вы уже находитесь в начале интервью  ', 'rus'),
(NULL, 'already_at_end_of_interview', 'Вы уже находитесь в конце интервью. Вновь благодарим Вас.  ', 'rus'),
(NULL, 'and', 'и  ', 'rus'),
(NULL, 'answerChoices_must_be_specified', 'Пожалуйста, уточните Ваш вариант ответ на вопрос  ', 'rus'),
(NULL, 'answerChoice_value_already_used', 'Данный вариант ответа уже использовался  ', 'rus'),
(NULL, 'answerOptions_column_missing', 'отсутствует колонка вариантов ответа на вопрос  ', 'rus'),
(NULL, 'answer_this_question', 'Пожалуйста, ответьте на данный вопрос  ', 'rus'),
(NULL, 'before_proceeding', 'Перед тем как перейти к  ', 'rus'),
(NULL, 'closing_braces', 'закрывающая фигурная скобка', 'rus'),
(NULL, 'column', 'колонка  ', 'rus'),
(NULL, 'conceptName_may_not_begin_with_a_digit', 'переменная conceptName не может начинаться с цифры \'_\':  ', 'rus'),
(NULL, 'CURRENT_QUESTIONS', 'Текущие вопросы', 'rus'),
(NULL, 'DATE', 'Дата', 'rus'),
(NULL, 'DAY', 'День', 'rus'),
(NULL, 'dependencies_column_is_missing', 'отсутствует колонка зависимостей значений  ', 'rus'),
(NULL, 'disallowed_for_security_reasons', 'отказано в доступе по причинам безопасности  ', 'rus'),
(NULL, 'does_not_exist', 'не существует  ', 'rus'),
(NULL, 'ending_tags_may_not_have_attribute_value_pairs', 'завершающие тэги не имеют соответствующей пары либо значения', 'rus'),
(NULL, 'Enter_a_comment_for_this_question', 'Введите свой комментарий к ответу на данный вопрос  ', 'rus'),
(NULL, 'Enter_password_for_Administrative_Mode', 'Введите пароль для входа в режим Администратора', 'rus'),
(NULL, 'entry_into_admin_mode_disallowed', 'Во входе в режим Администратора отказано  ', 'rus'),
(NULL, 'error_accessing_file', 'ошибка при доступе к файлу:', 'rus'),
(NULL, 'error_building_sorted_list_of_interviews', 'Ошибка при построении листа вывода данных интервью', 'rus'),
(NULL, 'error_closing_file', 'Ошибка при закрытии файла:', 'rus'),
(NULL, 'error_closing_reader', 'Ошибка при закрытии режима чтения:', 'rus'),
(NULL, 'error_closing_writer', 'Ошибка при закрытии режима ввода данных:  ', 'rus'),
(NULL, 'error_file', 'Ошибка: файл', 'rus'),
(NULL, 'error_getting_list_of_available_interviews', 'Ошибка при получении списка доступных опросов', 'rus'),
(NULL, 'Error_loading_datafile', 'Ошибка при загрузке файла данных ', 'rus'),
(NULL, 'error_null_filename', 'Ошибка – отсутствует имя файла', 'rus'),
(NULL, 'error_parsing_time', 'Ошибка при анализе временных показателей', 'rus'),
(NULL, 'Error_reading_from', 'Ошибка при чтении с', 'rus'),
(NULL, 'error_writing_to', 'Ошибка при попытке записи на', 'rus'),
(NULL, 'evals_disallowed_within_question_block', 'Выражение для вычисления не приемлемо внутри блока вопроса ', 'rus'),
(NULL, 'evaluate_expr', ' Выражение для вычисления', 'rus'),
(NULL, 'evaluations_disallowed_within_block', '\'e\' ввод выражений для вычисления в данной строке запрещен  ', 'rus'),
(NULL, 'EVIDENCE_AREA', 'ОБЛАСТЬ ДАННЫХ  ', 'rus'),
(NULL, 'expected_equals_sign', 'ожидаемый знак равенства в  ', 'rus'),
(NULL, 'expected_start_of_a_string', ' предполагается начало ряда значений', 'rus'),
(NULL, 'expects', '() ожидается ', 'rus'),
(NULL, 'extra_closing_brace', 'Лишняя закрывающая скобка', 'rus'),
(NULL, 'extra_closing_brace_at_line', 'лишняя закрывающая скобка в строке  ', 'rus'),
(NULL, 'extra_opening_brace', 'лишняя открывающая скобка', 'rus'),
(NULL, 'function', 'функция  ', 'rus'),
(NULL, 'Help', 'Помощь', 'rus'),
(NULL, 'HOUR', 'Час ', 'rus'),
(NULL, 'incorrect_password', 'Неверный пароль. Пожалуйста, повторите ввод ', 'rus'),
(NULL, 'incorrect_password_for_admin_mode', 'Неверный пароль для входа в режим Администратора', 'rus'),
(NULL, 'incorrect_syntax_for', 'Синтаксическая ошибка  ', 'rus'),
(NULL, 'inserting_missing_endTag_for', 'Вставьте недостающий закрывающий тэг для  ', 'rus'),
(NULL, 'Internal_error__Unexpected_data_format', 'Внутренняя ошибка: Неправильный формат данных:  ', 'rus'),
(NULL, 'interview_saved_successfully_as', 'Опрос успешно сохранен как  ', 'rus'),
(NULL, 'invalid_action_type', 'Неверное значение вопроса  ', 'rus'),
(NULL, 'invalid_answerType', 'Неверное значение ответа  ', 'rus'),
(NULL, 'invalid_dataType', 'Неверный тип данных:  ', 'rus'),
(NULL, 'invalid_end_tag', 'Неверный закрывающий тэг  ', 'rus'),
(NULL, 'invalid_formatting_mask', ' Неправильный формат маски:  ', 'rus'),
(NULL, 'invalid_node_at_step', 'Неверный узел в шагу:  ', 'rus'),
(NULL, 'invalid_number_for_starting_step', 'Неверное значение начального шага:  ', 'rus'),
(NULL, 'invalid_number_for_field_width', 'Неверное значение ширины поля:  ', 'rus'),
(NULL, 'invalid_questionOrEvalType', 'Неверное значение вопроса или ответа:  ', 'rus'),
(NULL, 'in_the_range', ' в диапазоне:  ', 'rus'),
(NULL, 'is_not_accessible', ' не приемлемо  ', 'rus'),
(NULL, 'is_not_a_directory', ' не является директорией  ', 'rus'),
(NULL, 'is_not_a_file', ' не является файлом  ', 'rus'),
(NULL, 'jump_to', 'перейти к:', 'rus'),
(NULL, 'languageNum_must_be_an_integer', 'значение переменной languageNum должен быть целым:  ', 'rus'),
(NULL, 'languageNum_must_be_in_range_zero_to', ' значение переменной languageNum должно быть в интервале (0-  ', 'rus'),
(NULL, 'line', 'строка  ', 'rus'),
(NULL, 'localName_may_not_begin_with_a_digit', ' переменная localName не может начинатся с цифры - начните ее с \'_\':  ', 'rus'),
(NULL, 'localName_must_be_specified', ' переменная localName не определена', 'rus'),
(NULL, 'localName_should_only_contain_letters_digits_and_underscores', ' переменная localName может включать в себя только буквы цифры и подчеркивания ', 'rus'),
(NULL, 'LogoMessage', 'Лого', 'rus'),
(NULL, 'max_less_than_min', 'максимальное значение меньше, чем минимальное занчение:  ', 'rus'),
(NULL, 'MINUTE', 'Минута ', 'rus'),
(NULL, 'mismatch_across_languages_in_answerType', 'несовпадение используемых языков при ответе на вопрос  ', 'rus'),
(NULL, 'mismatch_across_languages_in_number_of_answerChoices', 'несовпадение языков, используемых в вариантах ответа:  ', 'rus'),
(NULL, 'mismatch_across_languages_in_return_value_for_answerChoice_num', ' межъязыковое несоответствие в возвращаемом значении переменной answerChoice #  ', 'rus'),
(NULL, 'missing', 'отсутствует  ', 'rus'),
(NULL, 'missing_display_type', ' отсутствует отображаемый тип', 'rus'),
(NULL, 'missing_message_for_answerChoice_num', ' отсутствует текст сообщения для переменной answerChoice #  ', 'rus'),
(NULL, 'missing_value_or_message_for_answerChoice_num', ' отсутствует значение или текст сообщения для переменной answerChoice # ', 'rus'),
(NULL, 'MONTH', 'Месяц ', 'rus'),
(NULL, 'MONTH_NUM', 'Месяц (обозначьте порядковым номером) ', 'rus'),
(NULL, 'name_contains_invalid_character', 'имя содержит неверный символ:  ', 'rus'),
(NULL, 'new_variable_will_be_transient', 'значение новой переменной будет неопределенным:  ', 'rus'),
(NULL, 'next', 'Далее', 'rus'),
(NULL, 'node_does_not_exist', 'Узел не существует', 'rus'),
(NULL, 'node_does_not_exist_within_schedule', ' Узел не существует в задании(не найден индекс):  ', 'rus'),
(NULL, 'node_not_found', ' Узел не найден:  ', 'rus'),
(NULL, 'not_recognized', ' не распознается [  ', 'rus'),
(NULL, 'not_yet_suppported___line', ' значение не поддерживается ___ строка  ', 'rus'),
(NULL, 'no_closing_right_angle_bracket', 'отсутствует правая закрывающая угловая скобка  ', 'rus'),
(NULL, 'no_syntax_errors_found', 'Синтаксические ошибки не обнаружены  ', 'rus'),
(NULL, 'null_datum', 'нулевое значение данной переменной  ', 'rus'),
(NULL, 'null_node', 'нулевое значение узла  ', 'rus'),
(NULL, 'null_node_at_index', 'нулевое значение в ряду #  ', 'rus'),
(NULL, 'NUMBER', 'Число', 'rus'),
(NULL, 'numLanguages_must_be_greater_than_zero', 'значение переменной numLanguages должно быть больше нуля:  ', 'rus'),
(NULL, 'OFF', 'ВЫКЛ  ', 'rus'),
(NULL, 'ON', 'ВКЛ ', 'rus'),
(NULL, 'opening_braces', 'открывающая скобка  ', 'rus'),
(NULL, 'or', 'или', 'rus'),
(NULL, 'or_restore_an_interview_in_progress', 'или восстановить текущее интервью/опрос:  ', 'rus'),
(NULL, 'parameters', 'значение(я)  ', 'rus'),
(NULL, 'please_answer_the_questions_listed_in', 'Пожалуйста, ответьте на указанный вопрос(ы)  ', 'rus'),
(NULL, 'Please_answer_this_question', 'Пожалуйста ответьте на данный вопрос ', 'rus'),
(NULL, 'please_enter_a', 'Пожалуйста, введите  ', 'rus'),
(NULL, 'please_select_an_interview', 'Пожалуйста, выберите опрос из списка:  ', 'rus'),
(NULL, 'prematurely_terminated_element', 'безвозвратно удаленный элемент- ожидается значение  ', 'rus'),
(NULL, 'previous', 'назад', 'rus'),
(NULL, 'questionOrEvalTypeField_must_exist', 'отсутствует вопрос или выражение для вычисления ', 'rus'),
(NULL, 'QUESTION_AREA', 'ПОЛЕ ВОПРОСОВ  ', 'rus'),
(NULL, 'RED', ' КРАСНЫЙ', 'rus'),
(NULL, 'rejecting_mismatched_endTag', 'отсутствует пропущенный завершающий тэг  ', 'rus'),
(NULL, 'reload_questions', 'перезагрузить вопросы', 'rus'),
(NULL, 'restart_clean', 'перезапустить (очистить)', 'rus'),
(NULL, 'RESTORE', 'ВОССТАНОВИТЬ', 'rus'),
(NULL, 'restoring_original_schedule', ' - восстановить изначальные значения данных  ', 'rus'),
(NULL, 'save_to', 'сохранить в:', 'rus'),
(NULL, 'schedule_restored_successfully', 'Данные успешно восстановлены  ', 'rus'),
(NULL, 'SECOND', 'Второй', 'rus'),
(NULL, 'select_new_interview', 'Выберите новый опрос', 'rus'),
(NULL, 'select_one_of_the_following', 'Выберите один из следующих вариантов ответа  ', 'rus'),
(NULL, 'Set_as_Not_Understood', 'Вопрос не понят', 'rus'),
(NULL, 'Set_as_Refused', 'Отказываюсь отвечать на данный вопрос', 'rus'),
(NULL, 'Set_as_Unknown', 'Не знаю ответ на данный вопрос', 'rus'),
(NULL, 'show_Syntax_Errors', 'Отобразить синтаксические ошибки', 'rus'),
(NULL, 'stack_underflow', ' переполнение стека', 'rus'),
(NULL, 'starting_nested_group_at_line', 'Предупреждение: вложенная группа начинается с открытой скобки в строке ', 'rus'),
(NULL, 'START', 'СТАРТ', 'rus'),
(NULL, 'STRING', 'ряд  syntax_error_creating_node= синтаксическая ошибка создания узла:  ', 'rus'),
(NULL, 'The_following_data_access_errors_were', 'Обнаружены следующие ошибки в доступе к данным', 'rus'),
(NULL, 'The_following_flow_errors_were_found', 'Обнаружены следующие логические ошибки  ', 'rus'),
(NULL, 'The_following_syntax_errors_were_found', 'В файле были обнаружены следующие синтаксические ошибки', 'rus'),
(NULL, 'the_interview_is_completed', 'Благодарим Вас за участие в опросе.<br/><br/>Нажмите<a href="JavaScript:top.close();">на эту ссылку</a> для того, чтобы закрыть окно браузера.', 'rus'),
(NULL, 'TIME', 'Время', 'rus'),
(NULL, 'tried_to_switch_to_unsupported_language', 'Вы пытаетесь переключиться на язык, неподдерживаемый в данной программе ', 'rus'),
(NULL, 'turn_debugMode', ' переключится в режим отладки', 'rus'),
(NULL, 'turn_developerMode', ' переключится в режим разработки', 'rus'),
(NULL, 'turn_showQuestionNum', ' отобразить вопросы, в которых допущена ошибка ', 'rus'),
(NULL, 'unable_to_access', 'Невозможно получить доступ', 'rus'),
(NULL, 'unable_to_find_or_access_schedule', 'Невозможно найти или получить доступ к инструменту  ', 'rus'),
(NULL, 'Unable_to_write_schedule_file', 'Невозможно записать данные в файл:  ', 'rus'),
(NULL, 'unary_tags_may_not_have_closing_tags', 'унарные тэги не могут иметь закрывающих тэгов  ', 'rus'),
(NULL, 'undefined_variable', 'значение переменной не определено  ', 'rus'),
(NULL, 'unexpected_error', 'Неизвестная ошибка:  ', 'rus'),
(NULL, 'Unexpected_error_reading_from', 'Неизвестная ошибка при чтении с  ', 'rus'),
(NULL, 'unexpected_error_while_HTMLizing_string', 'неизвестная ошибка при конвертации файла в формат HTML  ', 'rus'),
(NULL, 'unknown_actionType_at_line', 'неизвестный тип ответа в строке  ', 'rus'),
(NULL, 'unknown_node', 'неизвестный узел  ', 'rus'),
(NULL, 'unknown_special_datatype', 'неизвестный тип данных  ', 'rus'),
(NULL, 'unsupported_function', 'неподдерживаемая функция  ', 'rus'),
(NULL, 'unterminated_escaped_character', 'Нетерминальный Escape символ', 'rus'),
(NULL, 'WEEKDAY', 'День недели ', 'rus'),
(NULL, 'YEAR', 'ГОД', 'rus'),
(NULL, 'at_index', 'по показателю', 'rus'),
(NULL, 'index_too_high', 'показатель слишком высокий', 'rus'),
(NULL, 'index_too_low', 'показатель слишком низкий', 'rus'),
(NULL, 'expects', 'ожидается ', 'rus'),
(NULL, 'function', 'функция', 'rus'),
(NULL, 'parameters', 'параметры', 'rus'),
(NULL, 'got', 'перейти к', 'rus'),
(NULL, 'error_changing_filenames', 'ошибка при изменении имени файла ', 'rus'),
(NULL, 'already_exists', 'данное значение уже существует', 'rus'),
(NULL, 'unable_to_move_event_logs', 'невозможно перенести лог в указанное местоположение ', 'rus'),
(NULL, 'sign_schedule', 'отметить и сохранить инструмент', 'rus'),
(NULL, 'signed_schedule_saved_as', 'отмеченный инструмент сохранен как', 'rus'),
(NULL, 'unable_to_save_signed_schedule', 'невозможно сохранить отмеченный инструмент', 'rus'),
(NULL, 'jumpToFirstUnasked', 'перейти к первому незаданному вопросу', 'rus'),
(NULL, 'suspendToFloppy', 'сохранить на диск', 'rus'),
(NULL, 'error_saving_data_to', 'ошибка при сохранении данных на ', 'rus'),
(NULL, 'error_saving_data_to_completed_dir', 'ошибка при сохранении данных в заполненную директорию', 'rus'),
(NULL, 'error_saving_data_to_floppy_dir', 'ошибка при сохранении данных в директорию на диске', 'rus'),
(NULL, 'your_browser_will_be_redirected_to', 'Ваш браузер будет перенаправлен ', 'rus'),
(NULL, 'in_three_seconds', 'в течение трех секунд.', 'rus'),
(NULL, 'or_you_can_click_here', 'либо нажмите сюда для немедленного перехода:  ', 'rus'),
(NULL, 'RESTORE_FROM_FLOPPY', 'СКОПИРОВАТЬ ОСТАВШИЕСЯ ОПРОСЫ С ДИСКА', 'rus'),
(NULL, 'or_restore_from_floppy', 'ИЛИ скопировать все оставшиеся опросы с диска. В этом случае они могут быть выбраны для восстановления:', 'rus'),
(NULL, 'toggle_EventCollection', ' включить режим захвата событий ', 'rus'),
(NULL, 'passwords_cannot_be_bypassed', 'невозможно обойти систему паролей', 'rus');

INSERT INTO i18n (i18n_id , label , val, iso3language )
VALUES
(NULL, 'Add_a_Comment', 'הוסף הערה o', 'heb'),
(NULL, 'alias_previously_used_on_line', 'alias previously used on line  ', 'heb'),
(NULL, 'already_at_beginning', 'את/ה בתחילת הראיון ', 'heb'),
(NULL, 'already_at_end_of_interview', 'את/ה בסופו של הראיון; תודה על שיתוף הפעולה.  ', 'heb'),
(NULL, 'and', 'ו  ', 'heb'),
(NULL, 'answerChoices_must_be_specified', 'answerChoices must be specified  ', 'heb'),
(NULL, 'answerChoice_value_already_used', 'answerChoice value already used:  ', 'heb'),
(NULL, 'answerOptions_column_missing', 'answerOptions column is missing  ', 'heb'),
(NULL, 'answer_this_question', 'בבקשה, עני/ה על שאלה זו ', 'heb'),
(NULL, 'before_proceeding', 'לפני שתמשיך', 'heb'),
(NULL, 'closing_braces', ' closing brace(s)  ', 'heb'),
(NULL, 'column', ' column  ', 'heb'),
(NULL, 'conceptName_may_not_begin_with_a_digit', 'conceptName may not begin with a digit - prepending \'_\':  ', 'heb'),
(NULL, 'CURRENT_QUESTIONS', 'CURRENT QUESTION(s)  ', 'heb'),
(NULL, 'DATE', 'תאריך', 'heb'),
(NULL, 'DAY', 'יום', 'heb'),
(NULL, 'dependencies_column_is_missing', 'dependencies column is missing  ', 'heb'),
(NULL, 'disallowed_for_security_reasons', 'disallowed for security reasons  ', 'heb'),
(NULL, 'does_not_exist', 'לא קיים ', 'heb'),
(NULL, 'ending_tags_may_not_have_attribute_value_pairs', 'ending tags may not have attribute values pairs  ', 'heb'),
(NULL, 'Enter_a_comment_for_this_question', 'הכנס הערה או התייחסות לשאלה זו ', 'heb'),
(NULL, 'Enter_password_for_Administrative_Mode', 'הקלד סיסמא  ', 'heb'),
(NULL, 'entry_into_admin_mode_disallowed', 'You do not currently have permission to be in Admin Mode  ', 'heb'),
(NULL, 'error_accessing_file', 'error accessing file:  ', 'heb'),
(NULL, 'error_building_sorted_list_of_interviews', 'Error building sorted list of interviews:  ', 'heb'),
(NULL, 'error_closing_file', 'שגיאה, המסמך נסגר:  ', 'heb'),
(NULL, 'error_closing_reader', 'error closing reader:  ', 'heb'),
(NULL, 'error_closing_writer', 'Error closing writer:  ', 'heb'),
(NULL, 'error_file', 'Error: file  ', 'heb'),
(NULL, 'error_getting_list_of_available_interviews', 'שגיאה, קבלת רשימה של הראיונות הזמינים:  ', 'heb'),
(NULL, 'Error_loading_datafile', 'Error loading datafile:  ', 'heb'),
(NULL, 'error_null_filename', 'Error: null filename  ', 'heb'),
(NULL, 'error_parsing_time', 'Error parsing time  ', 'heb'),
(NULL, 'Error_reading_from', 'Error reading from ', 'heb'),
(NULL, 'error_writing_to', 'Error writing to  ', 'heb'),
(NULL, 'evals_disallowed_within_question_block', 'Should not have expression evaluations within a query block (brace level  ', 'heb'),
(NULL, 'evaluate_expr', 'evaluate expr', 'heb'),
(NULL, 'evaluations_disallowed_within_block', '\'e\' actionTypes not allowed within a group of nodes - line  ', 'heb'),
(NULL, 'EVIDENCE_AREA', 'EVIDENCE AREA  ', 'heb'),
(NULL, 'expected_equals_sign', 'expected equals sign in  ', 'heb'),
(NULL, 'expected_start_of_a_string', 'expected the start of a string in  ', 'heb'),
(NULL, 'expects', '() expects  ', 'heb'),
(NULL, 'extra_closing_brace', 'Extra closing brace  ', 'heb'),
(NULL, 'extra_closing_brace_at_line', 'extra closing brace - line  ', 'heb'),
(NULL, 'extra_opening_brace', 'extra opening brace  ', 'heb'),
(NULL, 'function', 'function  ', 'heb'),
(NULL, 'Help', 'Help', 'heb'),
(NULL, 'HOUR', 'Hour ', 'heb'),
(NULL, 'incorrect_password', 'Incorrect password.  Please try again.  ', 'heb'),
(NULL, 'incorrect_password_for_admin_mode', 'Incorrect password to enter Administrative Mode  ', 'heb'),
(NULL, 'incorrect_syntax_for', 'Incorrect syntax for  ', 'heb'),
(NULL, 'inserting_missing_endTag_for', 'inserting missing endTag for  ', 'heb'),
(NULL, 'Internal_error__Unexpected_data_format', 'Internal error: Unexpected data format:  ', 'heb'),
(NULL, 'interview_saved_successfully_as', 'Interview saved successfully as  ', 'heb'),
(NULL, 'invalid_action_type', 'Invalid action type  ', 'heb'),
(NULL, 'invalid_answerType', 'invalid answerType  ', 'heb'),
(NULL, 'invalid_dataType', 'Invalid datum type:  ', 'heb'),
(NULL, 'invalid_end_tag', 'invalid end tag  ', 'heb'),
(NULL, 'invalid_formatting_mask', 'Invalid formatting mask:  ', 'heb'),
(NULL, 'invalid_node_at_step', 'Invalid node at step  ', 'heb'),
(NULL, 'invalid_number_for_starting_step', 'Invalid number for starting step:  ', 'heb'),
(NULL, 'invalid_number_for_field_width', 'Invalid number for field width:  ', 'heb'),
(NULL, 'invalid_questionOrEvalType', 'Invalid questionOrEvalType:  ', 'heb'),
(NULL, 'in_the_range', ' בטווח:  ', 'heb'),
(NULL, 'is_not_accessible', ' is not accessible  ', 'heb'),
(NULL, 'is_not_a_directory', ' is not a directory  ', 'heb'),
(NULL, 'is_not_a_file', ' is not a file  ', 'heb'),
(NULL, 'jump_to', 'Jump To:', 'heb'),
(NULL, 'languageNum_must_be_an_integer', 'languageNum must be an integer:  ', 'heb'),
(NULL, 'languageNum_must_be_in_range_zero_to', 'languageNum must be in range (0 -  ', 'heb'),
(NULL, 'line', 'line  ', 'heb'),
(NULL, 'localName_may_not_begin_with_a_digit', 'localName may not begin with a digit - prepending \'_\':  ', 'heb'),
(NULL, 'localName_must_be_specified', 'localName must be specified  ', 'heb'),
(NULL, 'localName_should_only_contain_letters_digits_and_underscores', 'localName should only contain letters, digits, and underscores ', 'heb'),
(NULL, 'LogoMessage', 'Logo', 'heb'),
(NULL, 'max_less_than_min', 'max value less than min value:  ', 'heb'),
(NULL, 'MINUTE', 'Minute ', 'heb'),
(NULL, 'mismatch_across_languages_in_answerType', 'mismatch across languages in answerType  ', 'heb'),
(NULL, 'mismatch_across_languages_in_number_of_answerChoices', 'mismatch across languages in number of answerChoices:  ', 'heb'),
(NULL, 'mismatch_across_languages_in_return_value_for_answerChoice_num', 'mismatch across languages in return value for answerChoice #  ', 'heb'),
(NULL, 'missing', 'missing  ', 'heb'),
(NULL, 'missing_display_type', 'missing display type  ', 'heb'),
(NULL, 'missing_message_for_answerChoice_num', 'missing message for answerChoice #  ', 'heb'),
(NULL, 'missing_value_or_message_for_answerChoice_num', 'Missing value or message for answerChoice #  ', 'heb'),
(NULL, 'MONTH', 'Month  חודש', 'heb'),
(NULL, 'MONTH_NUM', 'בספרות ', 'heb'),
(NULL, 'name_contains_invalid_character', 'name contains invalid character:  ', 'heb'),
(NULL, 'new_variable_will_be_transient', 'new variable will be transient:  ', 'heb'),
(NULL, 'next', 'הבא', 'heb'),
(NULL, 'node_does_not_exist', 'Node does not exist  ', 'heb'),
(NULL, 'node_does_not_exist_within_schedule', 'Unable to find index for node:  ', 'heb'),
(NULL, 'node_not_found', 'Node not found:  ', 'heb'),
(NULL, 'not_recognized', ' not recognized [  ', 'heb'),
(NULL, 'not_yet_suppported___line', ' not yet suppported - line  ', 'heb'),
(NULL, 'no_closing_right_angle_bracket', 'no closing right angle bracket  ', 'heb'),
(NULL, 'no_syntax_errors_found', 'No syntax errors were found  ', 'heb'),
(NULL, 'null_datum', 'null Datum  ', 'heb'),
(NULL, 'null_node', 'null Node name  ', 'heb'),
(NULL, 'null_node_at_index', 'null node at index #  ', 'heb'),
(NULL, 'NUMBER', 'מספר ', 'heb'),
(NULL, 'numLanguages_must_be_greater_than_zero', 'numLanguages must be greater than zero:  ', 'heb'),
(NULL, 'OFF', 'OFF  ', 'heb'),
(NULL, 'ON', 'ON  ', 'heb'),
(NULL, 'opening_braces', ' opening braces  ', 'heb'),
(NULL, 'or', 'או  ', 'heb'),
(NULL, 'or_restore_an_interview_in_progress', 'או, חדש הראיון שבתהליך:  ', 'heb'),
(NULL, 'parameters', ' parameter(s)  ', 'heb'),
(NULL, 'please_answer_the_questions_listed_in', 'בבקשה ענה/י על השאלה המסומנת ', 'heb'),
(NULL, 'Please_answer_this_question', 'ענה לשאלה זו ', 'heb'),
(NULL, 'please_enter_a', 'אנא הכנס  ', 'heb'),
(NULL, 'please_select_an_interview', 'Please select an interview:  ', 'heb'),
(NULL, 'prematurely_terminated_element', 'prematurely terminated element - expecting  ', 'heb'),
(NULL, 'previous', 'הקודם', 'heb'),
(NULL, 'questionOrEvalTypeField_must_exist', 'questionOrEvalTypeField must be exist  ', 'heb'),
(NULL, 'QUESTION_AREA', 'QUESTION AREA  ', 'heb'),
(NULL, 'RED', ' באדום  ', 'heb'),
(NULL, 'rejecting_mismatched_endTag', 'rejecting mismatched endTag  ', 'heb'),
(NULL, 'reload_questions', 'reload questions', 'heb'),
(NULL, 'restart_clean', 'restart (clean)', 'heb'),
(NULL, 'RESTORE', 'RESTORE', 'heb'),
(NULL, 'restoring_original_schedule', ' - restoring original schedule  ', 'heb'),
(NULL, 'save_to', 'save to:', 'heb'),
(NULL, 'schedule_restored_successfully', 'Schedule restored successfully  ', 'heb'),
(NULL, 'SECOND', 'Second ', 'heb'),
(NULL, 'select_new_interview', 'Select New Interview', 'heb'),
(NULL, 'select_one_of_the_following', '--בחר/י אחת מהאפשרויות הבאות--  ', 'heb'),
(NULL, 'Set_as_Not_Understood', 'אינו מובן ', 'heb'),
(NULL, 'Set_as_Refused', 'מסרב/ת', 'heb'),
(NULL, 'Set_as_Unknown', 'לא ידוע', 'heb'),
(NULL, 'show_Syntax_Errors', 'show Syntax Errors', 'heb'),
(NULL, 'stack_underflow', 'stack underflow  ', 'heb'),
(NULL, 'starting_nested_group_at_line', 'Warning - starting nested group (opening brace) at line ', 'heb'),
(NULL, 'START', 'START', 'heb'),
(NULL, 'STRING', 'String ', 'heb'),
(NULL, 'syntax_error_creating_node', 'Syntax error creating node:  ', 'heb'),
(NULL, 'The_following_data_access_errors_were', 'The following data access errors were found  ', 'heb'),
(NULL, 'The_following_flow_errors_were_found', 'The following flow errors were found  ', 'heb'),
(NULL, 'The_following_syntax_errors_were_found', 'The following syntax errors were found in file  ', 'heb'),
(NULL, 'the_interview_is_completed', 'Thank you for using our survey.<br/><br/>Click <a href="JavaScript:top.close();">here</a> to close this browser window.', 'heb'),
(NULL, 'TIME', 'Time ', 'heb'),
(NULL, 'tried_to_switch_to_unsupported_language', 'Tried to switch to unsupported language  ', 'heb'),
(NULL, 'turn_debugMode', 'toggle debugMode', 'heb'),
(NULL, 'turn_developerMode', 'toggle developerMode', 'heb'),
(NULL, 'turn_showQuestionNum', 'toggle showQuestionNum', 'heb'),
(NULL, 'unable_to_access', 'Unable to access  ', 'heb'),
(NULL, 'unable_to_find_or_access_schedule', 'Unable to find or access schedule  ', 'heb'),
(NULL, 'Unable_to_write_schedule_file', 'Unable to write schedule file:  ', 'heb'),
(NULL, 'unary_tags_may_not_have_closing_tags', 'unary tags may not have closing tags  ', 'heb'),
(NULL, 'undefined_variable', 'undefined variable  ', 'heb'),
(NULL, 'unexpected_error', 'Internal error:  ', 'heb'),
(NULL, 'Unexpected_error_reading_from', 'Unexpected error reading from  ', 'heb'),
(NULL, 'unexpected_error_while_HTMLizing_string', 'Unexpected error while HTMLizing string  ', 'heb'),
(NULL, 'unknown_actionType_at_line', 'unknown actionType for node - line  ', 'heb'),
(NULL, 'unknown_node', 'unknown node  ', 'heb'),
(NULL, 'unknown_special_datatype', 'Unknown special datatype  ', 'heb'),
(NULL, 'unsupported_function', 'unsupported function  ', 'heb'),
(NULL, 'unterminated_escaped_character', 'unterminated escape character   ', 'heb'),
(NULL, 'WEEKDAY', 'יום בשבוע', 'heb'),
(NULL, 'YEAR', 'שנה', 'heb'),
(NULL, 'at_index', 'at index', 'heb'),
(NULL, 'index_too_high', 'index too high', 'heb'),
(NULL, 'index_too_low', 'index too low', 'heb'),
(NULL, 'expects', ' expects ', 'heb'),
(NULL, 'function', 'function ', 'heb'),
(NULL, 'parameters', ' parameters', 'heb'),
(NULL, 'got', ' got ', 'heb'),
(NULL, 'error_changing_filenames', 'error changing filenames ', 'heb'),
(NULL, 'already_exists', ' already exists', 'heb'),
(NULL, 'unable_to_move_event_logs', 'unable to move events logs to ', 'heb'),
(NULL, 'sign_schedule', 'sign and save schedule', 'heb'),
(NULL, 'signed_schedule_saved_as', 'signed schedule saved as ', 'heb'),
(NULL, 'unable_to_save_signed_schedule', 'unable to save signed schedule', 'heb'),
(NULL, 'jumpToFirstUnasked', 'עבור לפריט הבא ', 'heb'),
(NULL, 'suspendToFloppy', 'שמור על הדיסקט', 'heb'),
(NULL, 'error_saving_data_to', 'שגיאה בשמירת הנתונים על ', 'heb'),
(NULL, 'error_saving_data_to_completed_dir', 'שגיאה בשמירת הנתונים להשלמה dir', 'heb'),
(NULL, 'error_saving_data_to_floppy_dir', 'שגיאה בשמירת הנתונים על הדיסקט dir', 'heb'),
(NULL, 'your_browser_will_be_redirected_to', 'Your browser will be redirected to ', 'heb'),
(NULL, 'in_three_seconds', ' in three seconds.', 'heb'),
(NULL, 'or_you_can_click_here', 'Or, you can click here to go there immediately:  ', 'heb'),
(NULL, 'RESTORE_FROM_FLOPPY', 'COPY SUSPENDED INTERVIEWS FROM FLOPPY', 'heb'),
(NULL, 'or_restore_from_floppy', 'OR copy all of the suspended interviews from the floppy so they they can be selected to be restored:', 'heb'),
(NULL, 'toggle_EventCollection', 'toggle Event Capture', 'heb'),
(NULL, 'passwords_cannot_be_bypassed', 'passwords cannot be bypassed', 'heb')
;