/* Generated By:JJTree: Do not edit this line. C:\cvs5\Dialogix2007\Dialogix_J2EE\Dialogix\src\org\dianexus\triceps\parser\DialogixParserTreeConstants.java */

package org.dianexus.triceps.parser;

public interface DialogixParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTEXPRESSIONS = 1;
  public int JJTEXPRESSION = 2;
  public int JJTASSIGNMENTEXPRESSION = 3;
  public int JJTCONDITIONALEXPRESSION = 4;
  public int JJTLOGICALOREXPRESSION = 5;
  public int JJTLOGICALANDEXPRESSION = 6;
  public int JJTINCLUSIVEOREXPRESSION = 7;
  public int JJTEXCLUSIVEOREXPRESSION = 8;
  public int JJTANDEXPRESSION = 9;
  public int JJTEQUALITYEXPRESSION = 10;
  public int JJTINLISTEXPRESSION = 11;
  public int JJTRELATIONALEXPRESSION = 12;
  public int JJTADDITIVEEXPRESSION = 13;
  public int JJTMULTIPLICATIVEEXPRESSION = 14;
  public int JJTUNARYEXPRESSION = 15;
  public int JJTPRIMARYEXPRESSION = 16;
  public int JJTCONSTANT = 17;
  public int JJTFUNCTION = 18;
  public int JJTFUNCTIONPARAMETERS = 19;


  public String[] jjtNodeName = {
    "Statement",
    "Expressions",
    "Expression",
    "AssignmentExpression",
    "ConditionalExpression",
    "LogicalORExpression",
    "LogicalANDExpression",
    "InclusiveORExpression",
    "ExclusiveORExpression",
    "ANDExpression",
    "EqualityExpression",
    "InListExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PrimaryExpression",
    "Constant",
    "Function",
    "FunctionParameters",
  };
}
