/* Generated By:JJTree&JavaCC: Do not edit this line. DialogixParserConstants.java */
package org.dianexus.triceps.parser;

public interface DialogixParserConstants {

  int EOF = 0;
  int CHARACTER_LITERAL = 1;
  int STRING_LITERAL = 2;
  int PLUS = 3;
  int MINUS = 4;
  int NOT = 5;
  int MULTIPLY = 6;
  int DIVIDE = 7;
  int GT = 8;
  int GE = 9;
  int EQ = 10;
  int NEQ = 11;
  int LT = 12;
  int LE = 13;
  int CONCATENATE = 14;
  int ANDAND = 15;
  int OROR = 16;
  int MODULUS = 17;
  int XOR = 18;
  int AND = 19;
  int OR = 20;
  int ASSIGN = 21;
  int IN = 22;
  int QUEST = 23;
  int COLON = 24;
  int COMMA = 25;
  int LP = 26;
  int RP = 27;
  int LSB = 28;
  int RSB = 29;
  int LCB = 30;
  int RCB = 31;
  int SEMICOLON = 32;
  int INTEGER_LITERAL = 37;
  int DECIMAL_LITERAL = 38;
  int HEX_LITERAL = 39;
  int OCTAL_LITERAL = 40;
  int FLOATING_POINT_LITERAL = 41;
  int EXPONENT = 42;
  int NMTOKEN = 43;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"+\"",
    "\"-\"",
    "\"!\"",
    "\"*\"",
    "\"/\"",
    "<GT>",
    "<GE>",
    "<EQ>",
    "<NEQ>",
    "<LT>",
    "<LE>",
    "\".\"",
    "<ANDAND>",
    "<OROR>",
    "<MODULUS>",
    "<XOR>",
    "<AND>",
    "<OR>",
    "\"=\"",
    "\"in\"",
    "\"?\"",
    "\":\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<NMTOKEN>",
  };

}
